# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_trucks_app', '0002_auto_20160722_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilefoodtrucks',
            old_name='geom',
            new_name='point',
        ),
    ]
